name: Update README

on:
  push:
    paths:
      - examples/**
      - docker-compose.yaml
      - .github/templates/README.template.md

jobs:
  update:
    uses: codeshelldev/gh-actions/.github/workflows/readme-update.yml@main
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
